AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  url-shortener

  Sample SAM Template for url-shortener

Globals:
  Function:
    Timeout: 5

Resources:
  ShortenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: internal/app/shorten/
      Handler: handler
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /shorten
            Method: POST
      Environment:
        Variables:
          PARAM1: VALUE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UrlShortenerAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/shorten/"
  ShortenFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt ShortenFunction.Arn
  ShortenFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ShortenFunctionRole.Arn
