AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  url-shortener

  Sample SAM Template for url-shortener

Globals:
  Function:
    Timeout: 5
  Api:
    TracingEnabled: True
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Parameters:
  Env:
    Type: String
    AllowedValues:
      - development
      - production
  Region:
    Type: String
  StorageTableName:
    Type: String
  PathLength:
    Type: Number
  Endpoint:
    Type: String
  DDBEndpoint:
    Type: String

Resources:
  ShortenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: internal/app/shorten/
      Handler: handler
      Runtime: go1.x
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref StorageTable
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /shorten
            Method: POST
      Environment:
        Variables:
          ENV: !Ref Env
          REGION: !Ref Region
          STORAGE_TABLE_NAME: !Ref StorageTableName
          DDB_ENDPOINT: !Ref DDBEndpoint
          PATH_LENGTH: !Ref PathLength
          ENDPOINT: !Ref Endpoint

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: internal/app/redirect
      Handler: handler
      Runtime: go1.x
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref StorageTable
      Architectures:
        - x86_64
      Events:
        Shorten:
          Type: Api
          Properties:
            Path: /short/{key}
            Method: GET
      Environment:
        Variables:
          ENV: !Ref Env
          REGION: !Ref Region
          STORAGE_TABLE_NAME: !Ref StorageTableName
          DDB_ENDPOINT: !Ref DDBEndpoint
          ENDPOINT: !Ref Endpoint

  StorageTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Ref StorageTableName

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UrlShortenerAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/shorten/"
  ShortenFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt ShortenFunction.Arn
  ShortenFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ShortenFunctionRole.Arn
